### 전체 도서 상태 조회
GET localhost:8081/api/bookStatuses
Accept: application/json

### 도서 상태 생성
POST localhost:8081/api/bookStatuses
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJqb2huX2RvZV8xMjQiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTczNDkzOTc1NX0.HDpJcIoVnggL3fVbCrlJJCGeS3_DXFung9KtTVgPGi4

{
  "bookStatus": "판매중"
}

### 아이디로 조회
GET localhost:8081/api/bookStatuses/1
Accept: application/json