POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "categoryName": "Fiction"
}

### 다른 카테고리 추가
POST http://localhost:8081/api/categories
Content-Type: application/json

{
  "categoryName": "Novel"
}

### 서브 카테고리를 1차 카테고리에 삽입
POST http://localhost:8081/api/categories/1/subcategories/2
Content-Type: application/json

{
  "categoryName": "Science Fiction"
}

### 1차 카테고리와 서브 카테고리 한번에 조회
GET http://localhost:8081/api/categories

### 도서를 카테고리에 추가
POST http://localhost:8081/api/categories/1/books/1
