###
POST localhost:8081/api/search
Content-Type: application/json

{
  "bookId": 12345,
  "bookTitle": "Effective Java",
  "bookDescription": "A comprehensive guide to best practices in Java programming.",
  "authorsName": [
    "Joshua Bloch"
  ],
  "tagsName": [
    "Java",
    "Programming",
    "Best Practices"
  ],
  "publisherName": "Addison-Wesley",
  "bookStatus": "AVAILABLE",
  "bookIsbn": 9780134685991,
  "bookPubDate": "2018-01-01",
  "bookOriginPrice": 45000,
  "bookPrice": 40000,
  "bookWrappable": false,
  "bookView": 1200,
  "bookAmount": 50,
  "bookSellCount": 3000
}


### 통합 검색
GET localhost:8081/api/search?search=한강
Accept: application/json

### 제목으로 검색
#&page=1&size=10
GET localhost:8081/api/search?title=
Accept: application/json

### 저자로 검색
GET localhost:8081/api/search?author=
Accept: application/json

### 설명으로 검색
GET localhost:8081/api/search?description=
Accept: application/json

### 태그로 검색
GET localhost:8081/api/search?tag=
Accept: application/json

### isbn으로 검색
GET localhost:8081/api/search?isbn=
Accept: application/json

### 판매수 기준으로 정렬(베스트셀러)
GET localhost:8081/api/search
Accept: application/json

