###
POST localhost:8081/api/books
Content-Type: application/json

{
  "bookId": 1,
  "bookTitle": "book1",
  "bookDescription": "bookDescription1",
  "authors": [
    "author1",
    "author2"
  ],
  "publisherName": "publisher1",
  "bookStatusName": "bookStatus1",
  "tagName": "tag1",
  "isbn": 1111111111111,
  "bookSellCount": 1
}

### 제목으로 검색
#&page=1&size=10
GET localhost:8081/api/books/search/title?title=
Accept: application/json

### 저자로 검색
GET localhost:8081/api/books/search/author?author=
Accept: application/json

### 설명으로 검색
GET localhost:8081/api/books/search/description?description=
Accept: application/json

### 태그로 검색
GET localhost:8081/api/books/search/tag?tag=
Accept: application/json

### isbn으로 검색
GET localhost:8081/api/books/search/isbn?isbn=
Accept: application/json

### 판매수 기준으로 정렬(베스트셀러)
GET localhost:8081/api/books/search/sellCount
Accept: application/json

