###
POST localhost:8081/api/search
Content-Type: application/json

{
  "bookId": 1,
  "bookTitle": "Elasticsearch Basics",
  "bookDescription": "Learn Elasticsearch from scratch.",
  "authors": [
    {
      "authorId": 101,
      "authorName": "John Doe"
    },
    {
      "authorId": 102,
      "authorName": "Jane Smith"
    }
  ],
  "publisher": {
    "publisherId": 201,
    "publisherName": "Tech Books Publishing"
  },
  "bookStatus": {
    "statusId": 301,
    "statusName": "AVAILABLE"
  },
  "tags": [
    {
      "tagId": 401,
      "tagName": "search"
    },
    {
      "tagId": 402,
      "tagName": "elasticsearch"
    },
    {
      "tagId": 403,
      "tagName": "technology"
    }
  ],
  "isbn": 9780134438422,
  "bookPubDate": "2024-01-01",
  "bookOriginPrice": 30000,
  "bookPrice": 25000,
  "bookWrappable": true,
  "bookView": 120,
  "bookAmount": 100,
  "bookSellCount": 50,
  "categories": [
    {
      "categoryId": 501,
      "categoryName": "Technology"
    },
    {
      "categoryId": 502,
      "categoryName": "Programming"
    }
  ]
}

### 통합 검색
GET localhost:8081/api/search?search=ea
Accept: application/json

### 제목으로 검색
#&page=1&size=10
GET localhost:8081/api/search?title=
Accept: application/json

### 저자로 검색
GET localhost:8081/api/search?author=
Accept: application/json

### 설명으로 검색
GET localhost:8081/api/search?description=
Accept: application/json

### 태그로 검색
GET localhost:8081/api/search?tag=
Accept: application/json

### isbn으로 검색
GET localhost:8081/api/search?isbn=
Accept: application/json

### 판매수 기준으로 정렬(베스트셀러)
GET localhost:8081/api/search
Accept: application/json

