### 도서 상태 생성
POST localhost:8081/api/bookStatuses
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJqb2huX2RvZV8xMjQiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTczNDkzOTc1NX0.HDpJcIoVnggL3fVbCrlJJCGeS3_DXFung9KtTVgPGi4

{
  "bookStatus": "판매중"
}


### 출판사 생성
POST localhost:8081/api/publishers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJCZWFyZXIiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJqb2huX2RvZV8xMjQiLCJyb2xlIjoiUk9MRV9BRE1JTiIsImlhdCI6MTczNDkzOTc1NX0.HDpJcIoVnggL3fVbCrlJJCGeS3_DXFung9KtTVgPGi4

{
  "publisherName": "교보문고"
}

### 네이버
GET http://localhost:8081/api/naverApi?query=한강

### 알라딘
GET http://localhost:8081/api/aladinApi?query=김훈

### 알라딘 (elasticsearch 저장), 저장전에 도서 상태 확인
POST http://localhost:8081/api/aladinApi?query=한강&bookStatusId=1

###
POST http://localhost:8081/api/aladinApi?query=김영하&bookStatusId=1

###
POST http://localhost:8081/api/aladinApi?query=박경리&bookStatusId=1

### 전체 도서 목록 조회
GET http://localhost:8081/api/books?page=0
Accept: application/json






